name: _dangtrip
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.1
  dio: ^5.1.1
  flutter_secure_storage: ^8.0.0
  url_launcher: ^6.1.10
  json_annotation: ^4.8.0
  naver_map_plugin:
    git: https://github.com/LBSTECH/naver_map_plugin.git
  # google_maps_flutter: ^2.2.6
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
flutter:
  uses-material-design: true
  fonts:
    - family: Pretendard
      fonts:
        - asset: lib/assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Pretendard-Black.ttf
          weight: 900
  assets:
  - lib/assets/banner/AD_1.png
  - lib/assets/banner/AD_2.png
  - lib/assets/banner/AD_3.png
  - lib/assets/banner/AD_4.png
  - lib/assets/banner/AD_5.png
  - lib/assets/banner/detail_test.png
  - lib/assets/logo/location.gif
  - lib/assets/logo/dogType.png
  - lib/assets/logo/parking.png
  - lib/assets/event/kanu_dog.jpg
  - lib/assets/logo/splash.png
